# language: node_js
# dist: trusty
# addons:
#   chrome: stable
# notifications:
#   email: false
# cache:
#   directories:
#     - node_modules
# sudo: required
# node_js:
#   - "10.15.3"
# env:
#   global:
#     - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false
# before_install:
#   - "sysctl kernel.unprivileged_userns_clone=1"
#   # Launch XVFB
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
# install:
#   - npm install
# script:
#   - npm run test
language: node_js
node_js:
  - "9"
dist: trusty
sudo: false  
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test